// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.projectx;

import com.projectx.ViewCI;

privileged aspect ViewCI_Roo_JavaBean {
    
    public String ViewCI.getViewName() {
        return this.viewName;
    }
    
    public void ViewCI.setViewName(String viewName) {
        this.viewName = viewName;
    }
    
}
