// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.projectx;

import com.projectx.ViewCI;
import com.projectx.ViewCIDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ViewCIDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ViewCIDataOnDemand: @Component;
    
    private Random ViewCIDataOnDemand.rnd = new SecureRandom();
    
    private List<ViewCI> ViewCIDataOnDemand.data;
    
    public ViewCI ViewCIDataOnDemand.getNewTransientViewCI(int index) {
        ViewCI obj = new ViewCI();
        setViewName(obj, index);
        return obj;
    }
    
    public void ViewCIDataOnDemand.setViewName(ViewCI obj, int index) {
        String viewName = "viewName_" + index;
        obj.setViewName(viewName);
    }
    
    public ViewCI ViewCIDataOnDemand.getSpecificViewCI(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ViewCI obj = data.get(index);
        Long id = obj.getId();
        return ViewCI.findViewCI(id);
    }
    
    public ViewCI ViewCIDataOnDemand.getRandomViewCI() {
        init();
        ViewCI obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ViewCI.findViewCI(id);
    }
    
    public boolean ViewCIDataOnDemand.modifyViewCI(ViewCI obj) {
        return false;
    }
    
    public void ViewCIDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ViewCI.findViewCIEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ViewCI' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ViewCI>();
        for (int i = 0; i < 10; i++) {
            ViewCI obj = getNewTransientViewCI(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
