// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.projectx;

import com.projectx.ViewCI;
import com.projectx.ViewCIDataOnDemand;
import com.projectx.ViewCIIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ViewCIIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ViewCIIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ViewCIIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ViewCIIntegrationTest: @Transactional;
    
    @Autowired
    ViewCIDataOnDemand ViewCIIntegrationTest.dod;
    
    @Test
    public void ViewCIIntegrationTest.testCountViewCIs() {
        Assert.assertNotNull("Data on demand for 'ViewCI' failed to initialize correctly", dod.getRandomViewCI());
        long count = ViewCI.countViewCIs();
        Assert.assertTrue("Counter for 'ViewCI' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ViewCIIntegrationTest.testFindViewCI() {
        ViewCI obj = dod.getRandomViewCI();
        Assert.assertNotNull("Data on demand for 'ViewCI' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ViewCI' failed to provide an identifier", id);
        obj = ViewCI.findViewCI(id);
        Assert.assertNotNull("Find method for 'ViewCI' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ViewCI' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ViewCIIntegrationTest.testFindAllViewCIs() {
        Assert.assertNotNull("Data on demand for 'ViewCI' failed to initialize correctly", dod.getRandomViewCI());
        long count = ViewCI.countViewCIs();
        Assert.assertTrue("Too expensive to perform a find all test for 'ViewCI', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ViewCI> result = ViewCI.findAllViewCIs();
        Assert.assertNotNull("Find all method for 'ViewCI' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ViewCI' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ViewCIIntegrationTest.testFindViewCIEntries() {
        Assert.assertNotNull("Data on demand for 'ViewCI' failed to initialize correctly", dod.getRandomViewCI());
        long count = ViewCI.countViewCIs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ViewCI> result = ViewCI.findViewCIEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ViewCI' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ViewCI' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ViewCIIntegrationTest.testFlush() {
        ViewCI obj = dod.getRandomViewCI();
        Assert.assertNotNull("Data on demand for 'ViewCI' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ViewCI' failed to provide an identifier", id);
        obj = ViewCI.findViewCI(id);
        Assert.assertNotNull("Find method for 'ViewCI' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyViewCI(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ViewCI' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ViewCIIntegrationTest.testMergeUpdate() {
        ViewCI obj = dod.getRandomViewCI();
        Assert.assertNotNull("Data on demand for 'ViewCI' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ViewCI' failed to provide an identifier", id);
        obj = ViewCI.findViewCI(id);
        boolean modified =  dod.modifyViewCI(obj);
        Integer currentVersion = obj.getVersion();
        ViewCI merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ViewCI' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ViewCIIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ViewCI' failed to initialize correctly", dod.getRandomViewCI());
        ViewCI obj = dod.getNewTransientViewCI(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ViewCI' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ViewCI' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ViewCI' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ViewCIIntegrationTest.testRemove() {
        ViewCI obj = dod.getRandomViewCI();
        Assert.assertNotNull("Data on demand for 'ViewCI' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ViewCI' failed to provide an identifier", id);
        obj = ViewCI.findViewCI(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ViewCI' with identifier '" + id + "'", ViewCI.findViewCI(id));
    }
    
}
